{% set name = "pyminizip" %}
{% set version = "0.2.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyminizip-{{ version }}.tar.gz
  sha256: 95c3cb3ad838e1374534c8c3a4408e44eccc06598730c095de338d814fe09ccf

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - pyminizip
  commands:
    - pip check   # [unix and (python_impl != 'pypy')]
  requires:
    - pip

about:
  home: https://github.com/smihica/pyminizip
  summary: A minizip wrapper - To create a password encrypted zip file in python.
  license_file: COPYING.txt
  license: Zlib

extra:
  recipe-maintainers:
    - thewchan
